version: '3.8'
services:
  passengers-postgres:
    container_name: passengers-postgres
    image: postgres:15
    environment:
      POSTGRES_DB: test3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 336942
    ports:
      - "5433:5432"
    volumes:
      - passengers_data:/var/lib/postgresql/data
volumes:
  passengers_data:
