version: '3.8'
services:
  postgres:
    container_name: passengers-postgres
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - passengers_data:/var/lib/postgresql/data

  elasticsearch:
    container_name: elasticsearch1
    image: elasticsearch:7.16.1
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: kibana:7.16.1
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  logstash:
    container_name: logstash
    image: logstash:7.16.2
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  passengers_data:
  elastic_data:

networks:
  elk:
    driver: bridge