version: '3.8'
services:
  postgres:
    container_name: transportation-postgres
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - transportation_data:/var/lib/postgresql/data

volumes:
  transportation_data:
