version: '3.8'

services:

  cassandra:
    image: cassandra:latest
    container_name: trips-cassandra
    ports:
      - "${CASSANDRA_PORT}:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "TripsCluster"
      CASSANDRA_DC: "DC1"
      CASSANDRA_RACK: "RAC1"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
      CASSANDRA_START_RPC: "true"
      CASSANDRA_PASSWORD_SEEDER: "${CASSANDRA_PASSWORD}"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      retries: 10
    volumes:
      - trips_data:/var/lib/cassandra

volumes:
  trips_data:
